# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: hasyemiraws
email: hi@hasyemiraws.com
description:
  High Functional Introvert. Full Time Learner. Part time stalker. Front end enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hasyemiraws.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Hasyemi Rafsanjani Asyari"
tagline: high functional introvert.

paginate: 10
paginate_path: /:num/

twitter:
  username: hasyemiraws

logo: "/assets/images/logo-white.png"

social:
  name: Hasyemi Rafsanjani Asyari
  links:
    - https://twitter.com/hasyemiraws
    - https://www.facebook.com/hasyemi.rafsanjani
    - https://instagram.com/hasyemiraws
    - https://codepen.io/hasyemiraws
    - https://www.linkedin.com/in/hasyemirafsanjani
    - https://plus.google.com/+hasyemirafsanjaniasyari
    - https://github.com/hasyemiraws
    - https://www.youtube.com/channel/UCzvyjUsomu2sdTbuBJHA9ag

# social url
twitter_url: https://twitter.com/hasyemiraws
ig_url: https://instagram.com/hasyemiraws
fb_url: https://www.facebook.com/hasyemi.rafsanjani
youtube_url: https://www.youtube.com/channel/UCzvyjUsomu2sdTbuBJHA9ag
codepen_url: https://codepen.io/hasyemiraws
github_url:  hasyemiraws

permalink: /:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed  
  - jekyll-seo-tag  
  - jekyll-sitemap
  - jekyll-paginate   
  - jekyll-autoprefixer   
  - jekyll-polyglot

sass:
  style: compressed
  sass_dir: _sass

google_analytics: UA-108167393-1
google_site_verification: UA-108167393-1
google_adsense: ca-pub-9523208256804448

disqus:
  shortname: hasyemiraws

collections:
  book:
    output: true
    permalink: /book/:path/

include: ['.htaccess']

languages: ["en", "id"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
